### ISSUE TITLE
Doesn't build if multiple Connext target packages are installed

### ISSUE THREAD

**Issue by tmcguire-rti** [rticommunity/rmw_connextdds#95]
**System Info**

- _OS_
  - Ubuntu 22.04
-  ROS version Humble/binary
- *RTI Connext DDS 6.1.1
- *RMW version Humble

**Bug Description**

My Connext installation has two target libraries installed armv8Linux4gcc7.3.0 and x64Linux4gcc7.3.0. I perform the following commands
`source /opt/ros/humble/setup.bash
source /opt/rti/rti_connext_dds-6.1.1/resource/scripts/rtisetenv_x64Linux4gcc7.3.0.bash
cd /opt/rti/ros2_connextdds
rm -rf build install log
colcon build --symlink-install`

**Expected Behavior**

I expect the RMW to build for x64Linux4gcc7.3.0. I verified
CONNEXTDDS_ARCH=x64Linux4gcc7.3.0
CONNEXTDDS_DIR=/opt/rti/rti_connext_dds-6.1.1

However the build tries to link to the armv8 libraries.

```
$ colcon build --symlink-install
Starting >>> rti_connext_dds_cmake_module
Finished <<< rti_connext_dds_cmake_module [3.53s]                  
Starting >>> rmw_connextdds_common
--- stderr: rmw_connextdds_common                                
/usr/bin/ld: skipping incompatible /opt/rti/rti_connext_dds-6.1.1/lib/armv8Linux4gcc7.3.0/libnddsc.so when searching for -lnddsc
/usr/bin/ld: cannot find -lnddsc: No such file or directory
/usr/bin/ld: skipping incompatible /opt/rti/rti_connext_dds-6.1.1/lib/armv8Linux4gcc7.3.0/libnddsc.so when searching for -lnddsc
/usr/bin/ld: skipping incompatible /opt/rti/rti_connext_dds-6.1.1/lib/armv8Linux4gcc7.3.0/libnddscore.so when searching for -lnddscore
/usr/bin/ld: cannot find -lnddscore: No such file or directory
/usr/bin/ld: skipping incompatible /opt/rti/rti_connext_dds-6.1.1/lib/armv8Linux4gcc7.3.0/libnddscore.so when searching for -lnddscore
```

**How to Reproduce**

```
source /opt/ros/humble/setup.bash
source /opt/rti/rti_connext_dds-6.1.1/resource/scripts/rtisetenv_x64Linux4gcc7.3.0.bash
cd /opt/rti/ros2_connextdds
rm -rf build install log
colcon build --symlink-install`
```

**Workarounds**
I had to delete the armv8 lib directory to get it to build.

**Comment by asorbini** [comment]
I found an issue in the CMake build script and filed #100 to track it.

Variable `CONNEXTDDS_ARCH` should be read from the environment, but currently isn't. An easier workaround than deleting the additional architecture from the installation is to pass `CONNEXTDDS_ARCH` as a CMake argument instead of an environment variable, e.g.:

```sh
colcon build --cmake-args -DCONNEXTDDS_ARCH=x64Linux4gcc7.3.0
```

I'm closing this issue since #100 can be used to track the fix.
